import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@/styles/Clerk.css";
import logo from "@/images/recipes-logo.png";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ModeToggle";
import Link from "next/link";
import Image from "next/image";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html className="flex justify-center" lang="en">
        <body className="max-w-[800px] w-[800px] mt-14 flex flex-col">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <nav className=" z-[1] fixed top-0 left-0 w-full backdrop-blur-lg flex justify-center items-center p-2 px-4 border-b bg-black bg-opacity-15 dark:bg-white dark:bg-opacity-15">
                <div className="w-full max-w-[800px] flex items-center justify-between">
                  <Link href={"/feed"}>
                    <Image width={50} height={10} src={logo} alt={"logo"} />
                  </Link>
                  <div className="flex items-center gap-6">
                    <ul className="flex gap-3 ">
                      <li className="text-slate-400 hover:text-white">
                        <Link href={"/"}>Profile</Link>
                      </li>
                      <li className="text-slate-400 hover:text-white">
                        <Link href={"/feed"}>Feed</Link>
                      </li>
                      <li className="text-slate-400 hover:text-white">
                        <Link href={"/create"}>Create</Link>
                      </li>
                    </ul>
                    <div className="flex gap-2">
                      <UserButton />
                      <ModeToggle />
                    </div>
                  </div>
                </div>
              </nav>
              <Toaster />
            </SignedIn>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
